configs/components/pe-bolt-services.rb

There's a missing argument to `install_service` which should be nil that's causing systemv installs of pe-bolt-services to fail

(maint) Properly install bolt services on systems with sysv init

---

configs/components/pe-bolt-services.rb

This adds the `systemctl daemon-reload` call back for systemd platforms so that changes to any pe bolt services files will be automatically picked up when they're installed, if the service is already on the system.

(maint) Load service file changes on systemd platforms

---

configs/platforms/osx-10.13-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb

Previously bolt was being packaged with an outdated snapshot of homebrew that did not require non-root user during build process. This commit uses updated homebrew formulas by setting up a non-root user for packaging. See https://tickets.puppetlabs.com/browse/PA-2334 for upstream puppet-agent work.

(BOLT-1040) Build puppet-bolt on osx with homebrew formulas as non-root

---

configs/platforms/fedora-28-x86_64.rb
configs/platforms/fedora-29-x86_64.rb
configs/projects/puppet-bolt.rb

This commit adds bolt packaging for fedora. Note that fedora 29 uses build tools in the fedora image instead of internal tools used by fedora 29.

(BOLT-978) Package puppet-bolt for fedora

---

configs/components/rubygem-ffi.rb
configs/components/rubygem-minitar.rb
configs/projects/pe-bolt-server.rb

Latest puppet-runtime has compatible gem versions for ffi and minitar. This will allow the pe-bolt-server and the puppet-bolt packages to have the same version of minitar.

(maint) Use ffi and minitar versions from puppet-runtime

---

configs/components/rubygem-ffi.rb
configs/components/rubygem-minitar.rb
configs/projects/pe-bolt-server.rb

Reverts puppetlabs/bolt-vanagon#74 
The puppet-agent that pe-bolt-server installs against does not have the same ffi as in puppet-runtime.

Revert "(maint) Use ffi and minitar versions from puppet-runtime"

---

configs/platforms/fedora-28-x86_64.rb
configs/platforms/fedora-29-x86_64.rb

Previously every module defined in bolt's Puppetfile was downloaded by r10k from the forge. When a module specified to be download from github in https://github.com/puppetlabs/bolt/pull/863 it was discovered that the fedora platforms need to be provisioned with git.

(BOLT-978) Add git to fedora platforms

---

resources/files/windows/PuppetBolt/PuppetBolt.psm1

Prior to this change, passing JSON as a parameter value to Bolt was a
bit difficult and prone to error because of the formatting requirements
involved with getting a properly escaped JSON string into Ruby.
This change finds any double quote characters in a string argument and
properly escapes them before passing them as arguments to Bolt. This
should help not only with passing JSON, but in any other situation where
a set of quotes needs to be faithfully represented to Bolt when coming
from a PowerShell CLI environment.

(BOLT-159) Bolt commands triple quoting in PS

---

configs/components/rubygem-cri.rb
configs/components/rubygem-r10k.rb

Incorporate bug fixes and new features from r10k 3.1.1 into bolt packages. The `cri` gem also needs to be updated so satisfy new r10k version.

(BOLT-1106) Bump r10k major version

---

configs/components/bolt.json

In order to avoid bolt-vanagon CI failures in https://github.com/puppetlabs/bolt-vanagon/pull/82/commits/cfe0c542f5566c14d25aa2f6d422ee3488f6b935 a fork of the bolt project was referenced. This allowed the vanagon project to run, but after merging the corresponding PR to Bolt the job to update the reference failed to find the reference BOLT-1076 in the bolt project. This commit manually makes the update that the bolt component pipeline would have made.

(BOLT-1076) Manually restore the reference to bolt

---

configs/components/rubygem-puppet-resource_api.rb

In order to support apply on devices pull in the latest RSAPI gem.

(BOLT-645) Update puppet-resource_api to 1.8.1

---

configs/platforms/ubuntu-14.04-amd64.rb
configs/platforms/ubuntu-14.04-i386.rb

2019.1 (kearney) does not support ubuntu 14.04. For the 14.04 platform, only use 2019.0 apt repo from enterprise.deleiver.pl.net.

(maint) Only use 2019.0 apt repo for ubuntu 14.04

---

ext/build_defaults.yaml

In order to manage separate `build_defaullts` (specifically `rpm_targets`) between 2019.0 and 2019.1 separate branches for bolt-vanagon will be used. The problem is that `rpm_targets` controls what repos package promotion targets https://jenkins-compose.delivery.puppetlabs.net/job/Package-Promotion/9774/ . 2019.0 will fail when el8 is set as an `rpm_target` and the package wont get promoted when el8 is excluded (see https://puppet.slack.com/archives/CF3DYM9SL/p1554847038464100 ). This commit sets the rpm_targets for johnson.
The plan will be to short term maintain a johnson branch and leave kearney + future pointed at master and long term to move the PE specific config to a separate vanagon project.

(BOLT-1220) Package pe-bolt-server for el8

---

configs/components/bolt.json

When we cut a new johnson branch we lost promoting bolt updates. This manually adds latest ref.

(maint) manually add updated bolt ref

---

configs/platforms/osx-10.13-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb

The upstream puppet-runtime project where we describe bolt-runtime switched to building osx 10.13 and 10.14 runtimes from 10.12 to their respective templated (osx image) versions. https://github.com/puppetlabs/puppet-runtime/commit/8c44fbb87abed15bd069ffef51b0a1eb4e1bfff4 this commit updates bolt-vanagon to build on updated templates to match those runtimes.

(maint) Update base image to build osx 10.13/14

---

configs/projects/pe-bolt-server.rb

Forgot to check for this in the mergeup from the johnson branch -- this will be moot soon, since pe-bolt-server is moving to puppetlabs/pe-bolt-vanagon, but this will be necessary just to see CI pass before we do the removal.

(maint) Fix runtime tarball name for pe-bolt-server

---

ext/build_defaults.yaml

This commit updates the `repo_name` param to `puppet-enterprise-tools`. This is
a new repo that will contain non-Puppet-Platform tools (like Bolt) for use by
PE customers. Even though we explicitly override this variable at ship time,
this is a good sane default.

(RE-12370) Update repo names

---

configs/platforms/debian-8-i386.rb

This commit works around https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1685477.html , revert once upstream provider release a fix.

(PA_2757) Temporarily pin python for 32bit debian 8

---

ext/build_defaults.yaml

This commit adds some metadata for the ship_gem rake task to be able to ship a staged gem from builds.delivery.pl.net to rubygems.

(BOLT-1317) Update build_defaults for shipping gem

---

docker/.gitignore
docker/.rspec
docker/Gemfile
docker/Makefile
docker/README.md
docker/distelli-manifest.yml
docker/puppet-bolt/Dockerfile
docker/puppet-bolt/spec/dockerfile_spec.rb

This uses the same tooling / pattern as the puppet-agent-ubuntu
container. Would eventually want this set up in jenkins I think, but the
pipelines config was trivial to copy over so I stuck with that for now.
Still todo:

(BOLT-1303) Initial work to add a `puppet-bolt` docker container

---

docker/Makefile
docker/puppet-bolt/Dockerfile

Previously the puppet-enterprise-tools-release path was used for apt release repos. The `enterprise` string has been removed. This commit updates the dockerfile to pull from the updated repo path.

(BOLT-1407) Update apt-repo to pull bolt package from for dockerfile

---

configs/projects/puppet-bolt.rb

Change to upstream vanagon desables all shebang mangling for redhat 8. This commit removes unncessary code.

(maint) Do not disable shebang mangling for redhat 8

---

configs/components/bolt.rb
resources/files/posix/bolt_inventory_pdb_wrapper
resources/files/windows/PuppetBolt/PuppetBolt.psd1
resources/files/windows/PuppetBolt/PuppetBolt.psm1

Closes puppetlabs/bolt#1172
This adds a wrapper script for the `bolt-inventory-pdb` command similar
to the one we use for `bolt`. The script gets installed to
`/opt/puppetlabs/bin` and symlinked from `/usr/local/bin` which is
typically on the users path. This then calls the actual ruby script at
`/opt/puppetlabs/bolt/bin` to execute the bolt-inventory-pdb command.
This is currently only availbable for linux and osx platforms

(GH-1172) Make bolt-inventory-pdb executable out of the box

---

docker/puppet-bolt/Dockerfile

This commit updates the base image for the puppet-bolt container to ubuntu 1804. This change follows the rest of the dockerized puppet projects (most notably the puppet-agent container which this image is modeled after). https://github.com/puppetlabs/puppet-agent/commit/382446021b23712191723161e90da5d61f5955e7

(packaging) Update base image for puppet-bolt docker image to bionic

---

docker/puppet-bolt/Dockerfile
docker/puppet-bolt/spec/dockerfile_spec.rb

In some cases, the remote side of a Bolt run will render UTF-8 characters (for example, in `apply_prep`). Bolt's logging mechanism uses the the system locale, which defaults to POSIX, and will throw an exception if it encounters UTF-8. This change sets the locale of our container to UTF-8 globally, which remedies the problem.

(packaging) Set Docker container locale to UTF-8

---

resources/files/windows/PuppetBolt/PuppetBolt.psm1

This updates the Bolt PowerShell module to use scoped variables instead
of environment variables and set SSL-based environment variables prior
to each invocation of Bolt.
Previously, environment variables were used and the SSL-based variables were set only once, causing issues when running Bolt and PDK in succession.
Fixes puppetlabs/bolt#1402

(GH-1402) Set SSL env variables before running Bolt in PowerShell module

---

configs/components/bolt.rb
resources/files/posix/bolt_inventory_pdb_wrapper
resources/files/windows/PuppetBolt/PuppetBolt.psd1
resources/files/windows/PuppetBolt/PuppetBolt.psm1

The `bolt-inventory-pdb` command was removed in Bolt 2.0, so it no
longer is packaged with Bolt. This removes a wrapper script for
executing the command.

(maint) Remove bolt-inventory-pdb wrapper script

---

configs/platforms/osx-10.15-x86_64.rb

This adds the OSX 10.15 platform to the Bolt project, allowing packages
to be built for the platform.

(GH-1445) Add OSX 10.15 support

---

configs/platforms/ubuntu-20.04-amd64.rb

Part of puppetlabs/bolt#1782
Blocked by puppetlabs/puppet-runtime#335

(packaging) Build Ubuntu 20.04 puppet-bolt packages

---

resources/files/windows/PuppetBolt/PuppetBolt.psd1

Removes `FunctionsToExport` from the PowerShell module manifest file which allows the `Export-ModuleMember` statement inside the `pms1` module file to control what cmdlets are public.

(maint) Fix Powershell module export statement

---

configs/components/bolt.rb
configs/projects/puppet-bolt.rb

Adds the `PuppetBolt.psd1` manifest file that is built along with the `PuppetBolt.psm1` module file. This completes managing the PowerShell module creation process.

(maint) Add Powershell Module Manifest Template

---

configs/components/bolt.rb

[This update to Bolt](https://github.com/puppetlabs/bolt/pull/2011)
moves all Rake tasks to the `rakelib` directory, which rake
automatically loads. This includes moving the rake tasks used to
generate the Powershell module from `pwsh_module` to the new directory
where they are automatically loaded by Rake. This updates the command in
Bolt's component build to generate the Powershell module to load the
task from the new location by not specifying a file to load tasks from.

(GH-1998) Update powershell generation to work with new Rakelib

---

configs/components/bolt-create-ruby-tarballs.rb
configs/projects/puppet-bolt.rb
resources/files/install-tarballs/extract_all.rb
resources/files/install-tarballs/remove_all.rb
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb
resources/windows/wix/tarball.vbs

This PR increases the speed at which Bolt MSI installs complete by using tarballs of the included Ruby gems instead of tracking each file in the MSI table.
- Create tarballs of ruby gems for Windows
- Extract tarballs during MSI Installation
- Remove extracted files on MSI uninstall
Acceptance Criteria:
1. Install MSI built from this PR on a fresh machine without failure. Run example command
1. Install MSI built from this PR on a fresh machine without failure. Then uninstall from machine without failure. All files installed should be removed.
1. Install bolt 2.24.1, then install MSI built from this PR. Product should upgrade without failure. Run example command
1. Install bolt 2.24.1, then install MSI built from this PR, then uninstall. All files installed should be removed without …

Use Tarball method for MSI based packages

---

ext/build_defaults.yaml

The local gpg_key setting is overridden by the one in build data. The
current setting refers to the soon-to-be-expired key.
This commit removes the gpg_key setting from build_defaults.yaml as an
attempt to reduce confusion.

(RE-13450) Remove gpg_key from local repo

---

configs/components/bolt.rb
configs/projects/puppet-bolt.rb
resources/files/windows/bolt.bat
resources/windows/wix/componentgroup.wxs.erb
resources/windows/wix/directorylist.wxs.erb

Creates the files used in https://github.com/puppetlabs/bolt/pull/2532
Closes https://github.com/puppetlabs/bolt/issues/2551
1. Install the new MSI
2. Remove the `bolt` function declaration from `C:\Program Files\WindowsPowerShell\Modules\PuppetBolt\PuppetBolt.psm1` (this is removed in https://github.com/puppetlabs/bolt/pull/2532 but won't be pulled in this PR)
- `C:\Program Files\Puppet Labs\Bolt\bin\bolt.bat` has the same contents as the file in this PR
- The `PATH` environment variable contains `C:\Program Files\Puppet Labs\Bolt\bin`
- Any shell finds the `bolt` command
> Note: Any problems with argument parsing should be logged in https://github.com/puppetlabs/bolt/pull/2532

(maint) Move to bolt.bat

---

docker/puppet-bolt/spec/dockerfile_spec.rb

This updates the docker container spec tests to use the `--log-level
debug` option in Bolt commands instead of the unsupported `--debug`
option.

(maint) Use --log-level debug in docker spec tests

---

resources/files/windows/bolt.bat

This commit fixes the paths set to the core environment variables for the ruby environment the bolt commandline expects.
Commit 917bbb1c40175c7863fb1fa7d76ca86da3da3f04 which implemented this was a copy paste of the Puppet bat approach, but did not account for the different path structure Puppet has compared to bolt.
Fixes: https://github.com/puppetlabs/bolt/issues/2650

(maint) Fix bolt.bat file environment variables

---

configs/platforms/el-6-x86_64.rb

This updates the build process to build el-6 packages on RedHat 6.
Previously, el-6 packages were built on centos-6, but the upstream repo
for that platform was removed by centos. This same change can also be
found in
[puppet-runtime](https://github.com/puppetlabs/puppet-runtime/commit/3f69db4c9eeda808379155b8037c21d7a4fda18f#diff-477edc1e13621457ee11ef723b62d8cd43b8f4081add074859465a407c8cd842).

(maint) Build el-6 packages on RedHat 6

---

configs/components/bolt.rb

This updates the path to the generated PowerShell module files, which
were changed in puppetlabs/bolt#2727 .

(GH-2550) Update path to generated PowerShell module files

---

docker/Gemfile

The default branch for the pupperware repo is now `main` instead of
`master`. This updates the Gemfile for the Docker image build to use the
`main` branch for the pupperware repo instead of `master`.

(maint) Update ref for pupperware to 'main'

---

ext/build_defaults.yaml

The 'gpg_name' configuration setting has been long-deprecated and throws a noisy warning. Removing the noise.

(maint) remove obsolete 'gpg_name' configuration

---

configs/components/bolt.rb

This copies the Bash autocomplete script from the Bolt repository to the
system autocompletion directory `/etc/bash_completion.d/` if that
directory exists, so that Bolt autocompletes can be loaded without
requiring user action.

(hack) Copy Bash autocomplete script to directory to be loaded

---

configs/platforms/osx-11-x86_64.rb

This adds macoS 11 as a platform so Bolt packages can be built for it.

(GH-2855) Build bolt for macOS 11

---

configs/platforms/fedora-34-x86_64.rb

This adds Fedora 34 as a supported platform for Bolt.

(GH-2903) Build bolt for Fedora 34

---

configs/platforms/fedora-30-x86_64.rb
configs/platforms/fedora-31-x86_64.rb
configs/platforms/osx-10.14-x86_64.rb

The release engineering team is removing vanagon support for Fedora 30,
Fedora 31, and OSX 10.14, in addition to removing support for the Puppet
Agent. This means that Bolt can no longer build packages for these
platforms, so is removing them.

(maint) Remove unsupported platforms

---

resources/windows/wix/powershell.wxs.erb

This adds all of the Bolt builtin guides to the Bolt PowerShell module
so they can be used for `Get-Help bolt-#{topic}`.

(hack) Add Bolt builtin guides to PowerShell module

---

resources/files/posix/bolt_env_wrapper

The `bolt_env_wrapper` script unsets several environment variables to
make Bolt execution predictable. Unsetting these variables also means
they are unset when Bolt runs Ruby tasks and scripts over the local
transport, which is incidental to Bolt being written in Ruby. The env
wrapper now saves Ruby-related environment variables to new
`BOLT_ORIG_<env_var>` variables, which allows Bolt to restore the
original values when running over the local transport with
`bundled-ruby` set to false.

(GH-2922) Save unset environment variables

---

configs/components/bolt.rb
configs/projects/puppet-bolt.rb
resources/windows/wix/bootsnap.vbs
resources/windows/wix/bootsnap.wxs
resources/windows/wix/componentgroup.wxs.erb
resources/windows/wix/customactions.wxs.erb
resources/windows/wix/sequences.wxs.erb

This commit precompiles the Bootsnap compile cache when Bolt is
installed so that the cache is available on the first Bolt run, and
doesn't lead to that first run taking a long time. Bolt configures the
Bootsnap cache dir to be `$env:ProgramData/Puppetlabs/bolt`, and ensures
the user has permissions to that directory so that the cache can be
updated during Bolt runs after install.

(GH-2291) Create Bootsnap cache on install on Windows

---

docker/puppet-bolt/Dockerfile

puppet-bolt is not pushed to the Docker Hub since bolt 3.18.0.
Upon inspection the Dockerfile couldn't be linted anymore, with following error:
`Dockerfile:24 DL3047 info: Avoid use of wget without progress bar. Use `wget --progress=dot:giga <url>`.Or consider using `-q` or `-nv` (shorthands for `--quiet` or `--no-verbose`).
Makefile:47: recipe for target 'lint' failed`
This (small) fix; fixes the Dockerfile linting for puppet-bolt.

Fix puppet-bolt Dockerfile linting.

---

configs/platforms/windows-2012r2-x64.rb

`choco update` is removed in chocolatey 1.0, so we need to transition to
the proper command `choco upgrade`.

(maint) Use `choco upgrade` instead of deprecated `choco update`

---

Gemfile

This bumps the minimum version for the `packaging` gem to 0.105.0, as
Bolt packages are now available for el-9 and this is the earliest
version of the packaging gem that can build packages for that platform.
---
Support for el-9 added to the packaging gem [here](https://github.com/puppetlabs/packaging/commit/225fef5456f15b797ba839c2be4685d658d4f5b4)

(maint) Bump minimum version for packaging gem to 0.105

---

configs/platforms/osx-10.15-x86_64.rb
configs/platforms/osx-12-x86_64.rb

Reverts puppetlabs/bolt-vanagon#186 due to https://tickets.puppetlabs.com/browse/BOLT-1586

Revert "(maint) Build Bolt for macOS 12, remove macOS 10.15"

---

configs/components/gem-prune.rb

There was an error in the GEM_PATH set on https://github.com/puppetlabs/bolt-vanagon/pull/179 - corrected to point to the directory containing the project's gems rather than the gem binary.

(BOLT-1580) Gem pruning path correction

---

configs/platforms/fedora-32-x86_64.rb
configs/platforms/ubuntu-16.04-amd64.rb
configs/platforms/ubuntu-16.04-i386.rb

This removes Fedora 32 and Ubuntu 16.04 as supported platforms.

(maint) Remove EOL platforms

---

configs/projects/puppet-bolt.rb

This commit updates building bolt packages for fedora 36 with the same RPM package overrides as puppet agent. See https://github.com/puppetlabs/puppet-agent/pull/2270 for details.

(BOLT-1594) Support for fedora 36 bolt packages

---

resources/windows/wix/tarball.vbs

This commit removes the intermediate script constructed for installation from being written to the %TEMP% directory. Intead it is written to the same directory the script is being run from. This ensures users must be able to write to the directory this script is being run from (for example C:\windows\system32 instead of %TEMP%).

(PE-36810) Stop using dynamic tmp directory for batch script

---

resources/files/windows/bolt.bat

This commit follows the precedent set in the agent in the follwoing commit: https://github.com/puppetlabs/puppet-agent/commit/f46d20258e6c016ca2808243594c83968f5b4d0b While we are not building bolt for fips at this time, setting these envirinment variables ensures our vendored openssl is as isolated as possible from anything that may be on a target install. See the relevant information from the linked commit message:
By default, openssl sets `OPENSSL_CONF_INCLUDE` to a directory relative to the --openssldir configuration option set at compilation time. But on Windows that's under C:\ProgramFiles64Folder. To ensure, we only load configuration from the user-specified install directory, set the `OPENSSL_CONF_INCLUDE` directory in environment.bat, like we do for other OpenSSL paths. The …

(maint) Ensure legacy providers are loaded for bolt on windows

---

configs/platforms/ubuntu-24.04-amd64.rb

Currently Bolt is having issues on ubuntu24 where puppet is not being installed under /opt/puppetlabs/puppet causing Bolt apply to not work, so we have decided to temporarily remove ubuntu24 until this issue is solved

Remove ubuntu 24 platform
